services:
  db:
    image: postgres
    container_name: clickbeard_db
    restart: always
    environment:
      POSTGRES_USER: clickbeard
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: clickbeard_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: .
    container_name: clickbeard_backend
    restart: always
    environment:
      #DATABASE_URL: postgres://clickbeard:dev123@db:5432/clickbeard_db
      DATABASE_URL: postgresql://neondb_owner:npg_wIab4RiHl9gu@ep-late-credit-ac0805kb-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      PORT: 3333
      JWT_SECRET: NotSet
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run build && npm start"

volumes:
  postgres_data:
